// Modified by Variya 2026-09-11: light UI tokens shared by components and charts.
import { theme } from 'antd';
import type { ThemeConfig } from 'antd';

export const colors = {
  canvas: '#F5F6F8',
  surface: '#FFFFFF',
  text: '#252A34',
  muted: '#646B78',
  border: '#E1E4EA',
  accent: '#5966A6',
  success: '#34745A',
  warning: '#95631B',
  danger: '#B14444',
  grid: '#ECEEF2',
} as const;

export const fonts = {
  ui: '"Segoe UI Variable", "Segoe UI", "PingFang SC", "Microsoft YaHei", sans-serif',
  code: '"SF Mono", Consolas, Menlo, monospace',
} as const;
const fontFamily = fonts.ui;
const fontFamilyCode = fonts.code;
const selectedBg = '#EEF0F8';
const hoverBg = '#F1F3F6';
const focusShadow = '0 0 0 2px rgba(89, 102, 166, 0.16)';

export const lightTheme: ThemeConfig = {
  algorithm: theme.defaultAlgorithm,
  token: {
    colorPrimary: colors.accent,
    colorPrimaryHover: '#4D5A94',
    colorPrimaryActive: '#424E82',
    colorPrimaryBg: selectedBg,
    colorInfo: colors.accent,
    colorSuccess: colors.success,
    colorWarning: colors.warning,
    colorError: colors.danger,
    colorSuccessText: colors.success,
    colorWarningText: colors.warning,
    colorErrorText: colors.danger,
    colorInfoText: colors.accent,
    colorBgBase: colors.surface,
    colorBgContainer: colors.surface,
    colorBgElevated: colors.surface,
    colorBgLayout: colors.canvas,
    colorBgSpotlight: colors.surface,
    colorBgBlur: colors.surface,
    colorBgMask: 'rgba(37, 42, 52, 0.32)',
    colorTextBase: colors.text,
    colorText: colors.text,
    colorTextHeading: colors.text,
    colorTextSecondary: colors.muted,
    colorTextTertiary: colors.muted,
    colorTextQuaternary: '#9096A1',
    colorTextDescription: colors.muted,
    colorTextLabel: colors.muted,
    colorTextPlaceholder: colors.muted,
    colorTextDisabled: '#9096A1',
    colorTextLightSolid: colors.surface,
    colorIcon: colors.muted,
    colorIconHover: colors.text,
    colorBorder: colors.border,
    colorBorderSecondary: colors.border,
    colorSplit: colors.border,
    colorLink: colors.accent,
    colorLinkHover: '#4D5A94',
    colorLinkActive: '#424E82',
    colorFill: '#E9ECF1',
    colorFillSecondary: hoverBg,
    colorFillTertiary: colors.canvas,
    colorFillQuaternary: '#FAFBFC',
    colorFillContent: hoverBg,
    colorFillContentHover: '#E9ECF1',
    colorFillAlter: '#F8F9FB',
    colorBgContainerDisabled: colors.canvas,
    colorBgTextHover: hoverBg,
    colorBgTextActive: selectedBg,
    controlItemBgHover: hoverBg,
    controlItemBgActive: selectedBg,
    controlItemBgActiveHover: '#E5E8F3',
    controlOutline: 'rgba(89, 102, 166, 0.16)',
    borderRadius: 8,
    borderRadiusLG: 10,
    borderRadiusSM: 6,
    fontFamily,
    fontFamilyCode,
    fontSize: 14,
    fontSizeSM: 12,
    fontSizeHeading1: 36,
    fontSizeHeading2: 28,
    fontSizeHeading3: 22,
    fontSizeHeading4: 20,
    fontSizeHeading5: 18,
    fontWeightStrong: 600,
    lineHeight: 1.6,
    controlHeight: 36,
    controlHeightLG: 44,
    controlHeightSM: 28,
    boxShadow: '0 8px 24px rgba(37, 42, 52, 0.10)',
    boxShadowSecondary: '0 12px 36px rgba(37, 42, 52, 0.12)',
    boxShadowTertiary: '0 1px 4px rgba(37, 42, 52, 0.06)',
    wireframe: false,
  },
  components: {
    Layout: {
      headerBg: colors.surface,
      headerHeight: 68,
      headerPadding: '0 32px',
      bodyBg: colors.canvas,
      footerBg: colors.canvas,
    },
    Menu: {
      itemBg: colors.surface,
      popupBg: colors.surface,
      itemColor: colors.muted,
      itemHoverColor: colors.text,
      itemHoverBg: hoverBg,
      itemSelectedBg: selectedBg,
      itemSelectedColor: colors.accent,
      itemActiveBg: selectedBg,
      horizontalItemSelectedColor: colors.accent,
      horizontalItemHoverColor: colors.accent,
      itemBorderRadius: 6,
      activeBarBorderWidth: 0,
    },
    Card: {
      headerBg: 'transparent',
      headerFontSize: 16,
      headerFontSizeSM: 14,
      headerHeight: 52,
      headerHeightSM: 44,
      paddingLG: 20,
      paddingSM: 16,
    },
    Table: {
      headerBg: '#F8F9FB',
      headerColor: colors.muted,
      headerSplitColor: colors.border,
      borderColor: colors.border,
      rowHoverBg: '#F8F9FB',
      rowSelectedBg: selectedBg,
      rowSelectedHoverBg: '#E5E8F3',
      headerSortActiveBg: hoverBg,
      headerSortHoverBg: '#E9ECF1',
      bodySortBg: '#FAFBFC',
      footerBg: '#F8F9FB',
      footerColor: colors.muted,
      cellPaddingBlock: 12,
      cellPaddingInline: 16,
    },
    Statistic: { titleFontSize: 12, contentFontSize: 24 },
    Button: {
      fontWeight: 500,
      borderRadius: 6,
      primaryShadow: 'none',
      defaultShadow: 'none',
      dangerShadow: 'none',
      defaultBg: colors.surface,
      defaultColor: colors.text,
      defaultBorderColor: colors.border,
    },
    Input: {
      activeBg: colors.surface,
      hoverBg: colors.surface,
      activeBorderColor: colors.accent,
      hoverBorderColor: colors.accent,
      activeShadow: focusShadow,
    },
    InputNumber: {
      activeBg: colors.surface,
      hoverBg: colors.surface,
      activeBorderColor: colors.accent,
      hoverBorderColor: colors.accent,
      activeShadow: focusShadow,
    },
    Select: {
      selectorBg: colors.surface,
      optionSelectedBg: selectedBg,
      optionSelectedColor: colors.accent,
      optionSelectedFontWeight: 600,
      optionActiveBg: hoverBg,
    },
    Tag: { defaultBg: colors.canvas, defaultColor: colors.muted, fontSizeSM: 12 },
    Modal: { contentBg: colors.surface, headerBg: colors.surface, titleColor: colors.text },
    Drawer: { colorBgElevated: colors.surface },
    Tooltip: {
      colorBgSpotlight: colors.surface,
      colorTextLightSolid: colors.text,
      fontSize: 12,
    },
    Popover: { colorBgElevated: colors.surface, colorText: colors.text },
    Dropdown: { colorBgElevated: colors.surface },
    Alert: { defaultPadding: '12px 16px' },
    Segmented: {
      trackBg: '#EBEDF2',
      itemSelectedBg: colors.surface,
      itemSelectedColor: colors.text,
      itemColor: colors.muted,
      itemHoverColor: colors.text,
    },
    Collapse: { headerBg: '#F8F9FB', contentBg: colors.surface },
    Form: { labelColor: colors.text, labelFontSize: 14 },
    Divider: { colorSplit: colors.border },
    Spin: { colorPrimary: colors.accent },
    Progress: { defaultColor: colors.accent, remainingColor: colors.grid },
    Skeleton: { gradientFromColor: '#E9ECF1', gradientToColor: '#F5F6F8' },
    Tabs: { itemColor: colors.muted, itemSelectedColor: colors.accent, inkBarColor: colors.accent },
  },
};
